### ISSUE TITLE
npm run build result not working production 

### ISSUE THREAD

**Issue by jeremenichelli** [vuejs-templates/webpack-simple#11]
I didn't want to rise an issue on this because it could be a local problem and it would be a shame to bother maintainers with this, but couldn't find any similar problem in forums.

I've used this template which worked **great** locally _- kudos for that -_ but after building and including the dist folder in a repository the router never starts the app and there's no console error either.

Here's the link https://jeremenichelli.github.io/movies/result/vue

Any shed of light is appreciated since I'm planning to write about various frameworks including **Vue** 😃

**Comment by chrisvfritz** [comment]
You don't have `vue-router` installed, so it shouldn't work in development _or_ production right now. `npm install --save vue-router`, `npm run build`, then correct the link to `results` (with an `s`) and you'll be good.  😃  

In the future though, since the problem is specific to your code and does not affect a freshly generated project using this template, either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue) would be a better place for questions like this.

**Comment by jeremenichelli** [comment]
Thanks for checking that @chrisvfritz, I did install it but somehow didn't got to the `dependencies` inside the `package.json` file. It's weird the fact that it works on my computer, it still doesn't on the `gh-pages` address. and I checked the `build.js` file and it's there. I will move this to the forum. Thank you.

**Comment by chrisvfritz** [comment]
It doesn't look like you've rerun `npm run build` and commited the new `dist` after adding `vue-router` to dependencies. After that, you may also need to do a hard refresh as this template doesn't add asset hashes like the more complex Webpack template.

**Comment by jeremenichelli** [comment]
Hmm.. Any idea on how to do that hard refresh? It seems like build is throwking the same result though I don't really understand what's the exact problem 😢

**Comment by jeremenichelli** [comment]
I mean, what is that I should _manually_ do to actually reflect that change?

**Comment by chrisvfritz** [comment]
There isn't anything more that should need to be done to reflect a change. I unfortunately don't have time to take a deep dive into why your application might not be working, but I can leave you with this last thing I noticed at a quick glance. 

[The `activate` and `deactiveat` hooks](https://github.com/jeremenichelli/movies/blob/master/results/vue/src/views/search-view.vue#L55-L60) on your search page should theoretically never resolve, since they take a `transition` argument and one needs to call `transition.next()` to resolve. See [the vue-router docs](http://router.vuejs.org/en/pipeline/activate.html) for more. Hope this helps and that you're able to get your app working! 😃

**Comment by jeremenichelli** [comment]
It's ok @chrisvfritz, didn't expect anyone to waste their time with this specific debugging, it wouldn't feel right. I thank you for taking some of your time to take a quick look at it.

Since it's not throwing an error, my assumption is that the `root` view is not showing because of the path on the location of my GitHub page and it explains why locally it works on both **dev** and **production** mode.. The final test would be to put that solution in a server and see what happens.

Thanks again!

**Comment by recioRaszak** [comment]
Hey guys! Had exactly the same issue...

[solved] Router's working in dev but not in prod, because routes change their root...
Remember to remap your routes with /path-to/production or a relative path (don't know yet how, I've used absolute routes for my pre-prod test and it WORKED)

**Comment by schatekar** [comment]
@recioRaszak what do you mean by `remap your routes with /path-to/production or a relative path`? Can you explain with an example?

**Comment by recioRaszak** [comment]
@schatekar Hum... Some months had passed, I don't remember very well the thread... but the thing is, in the configuration file or router configuration, do not use "/" or "/app", <- relative paths. I was trying to say to use absolute paths "http://domain.com/sub-section-or-not/app/"...
