### ISSUE TITLE
Invalid configuration object - configuration.entry

### ISSUE THREAD

**Issue by markheath** [vuejs-templates/webpack-simple#136]
I have been unable to get the `webpack-simple` template working on my machine

```
$ vue init webpack-simple vuesimple
$ cd vuesimple
$ npm install
$ npm run dev
```

When I launch `npm run dev` I get the following error:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an object.
    * configuration.entry should be a string.
    * configuration.entry should NOT have duplicate items (items ## 1 and 3 are identical) ({
        "keyword": "uniqueItems",
        "dataPath": ".entry",
        "schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/uniqueItems",
        "params": {
          "i": 3,
          "j": 1
        },
        "message": "should NOT have duplicate items (items ## 1 and 3 are identical)",
        "schema": true,
        "parentSchema": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "data": [
          "D:\\Code\\web\\vuesimple\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8081",
          "webpack/hot/dev-server",
          "D:\\code\\web\\vuesimple\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "./src/main.js"
        ]
      }).
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
```

I've tried various things I found after googling for this error like updating npm and installing webpack-dev-server globally, but nothing so far has resolved it. Any pointers in the right direction would be greatly appreciated.

**Comment by markheath** [comment]
I've worked it out. The issue only occurs when running the commands in PowerShell. If I use a regular Windows command prompt it works fine.

**Comment by donorman** [comment]
+1
Same problem, same solution.

**Comment by dmfedotov** [comment]
+1 same

**Comment by alevans4** [comment]
I have had the same issue.  The issue is related to this issue with [webpack ](https://github.com/webpack/webpack/issues/4530) on windows.

Essentially, Powershell will allow you to change into a directory in a case-insensitive manner and if the case of the directory you are in is not the same as the actual name of the directory, then this error will be thrown. For example, if I have a directory called C:\Temp on disk and in Powershell I change into the directory using cd \temp, the resulting path in Powershell (using pwd for example) is C:\temp. Note the capitalization difference. When this happens, webpack will throw the error.

You can get this template to run in Powershell simply by navigating to the directory exactly as it exists on disk (ie cd \Temp).

I expect there is a way to set up the config file such that this can be ignored. I don't have time immediately, but if I get a chance later and no one else has fixed it yet, I'll make the attempt.
