### ISSUE TITLE
How to adapt boilerplate to use Sass

### ISSUE THREAD

**Issue by stursby** [vuejs-templates/webpack-simple#4]
I'm hoping this is an easy solve. I'm tying to use Sass (SCSS specifically) in my `.vue` file.

For example:

````
<style lang="sass" scoped>
$red: red;
body {
  background: $red;
}
</style>
````

I tried adding [jtangelder/sass-loader](https://github.com/jtangelder/sass-loader) in my `webpack.config.js` using a config like this:

````
{
  test: /\.scss$/,
  loaders: ['style', 'css', 'sass']
},
````

...but no luck.

Any ideas?

Thanks!

**Comment by stursby** [comment]
Hmmmm, I restarted Webpack a few times, and it seems to be working now using the above edits. Will close for now.

**Comment by SimulatedGREG** [comment]
I can't seem to get this working for me. Do you happen to have a working example @stursby I could look at, or at least the `webpack.config.js` file?

**Comment by chrisvfritz** [comment]
@SimulatedGREG With the latest version of the template (and using the latest `vue-cli`), is this working for you now? We've made quite a few updates to improve the compile-to-CSS language config.

**Comment by SimulatedGREG** [comment]
Still having no luck. Here's what I just tried...

Setup `webpack-simple` using `vue-cli@2.1.0`.
```
vue init webpack-simple test
cd test
npm install && npm install -D node-sass sass-loader
```
Then ran `npm run dev`. Server runs fine, and changes are hot reloading as expected. As soon as I add `lang="scss"` or `lang="sass"` to the `<style>` tag in `App.vue` I get errors.

```
ERROR in ./src/App.vue
Module not found: Error: Cannot resolve module 'scss' in /Users/gregholguin/Desktop/test/src
 @ ./src/App.vue 2:0-180
```

I thinking this might actually be an issue with `vue-loader` as other pre-processors seem to work, but am only able to use SASS/SCSS if I edit my `webpack.config.js` to include...
```js
vue: {
    loaders: {
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
      scss: 'vue-style-loader!css-loader!sass-loader'
    }
  }
```
...which is what the full `webpack` template is using. Sort of strange why I have to add this manually, as the documentation for `vue-loader` states this should work out-of-the-box. [**Docs**](http://vue-loader.vuejs.org/en/configurations/pre-processors.html)

**Comment by chrisvfritz** [comment]
It's expected that `lang="scss"` will fail because there is no `scss-loader` installed. And if you specify `lang="sass"`, it'll work with the unindented syntax, which is `sass-loader`'s default. I just confirmed that this works with the latest template:

``` vue
<style lang="sass">
body {
  background: orange;
  font-family: Helvetica, sans-serif;
  h1 {
    color: blue;
  }
}
</style>
```

**Comment by SimulatedGREG** [comment]
Okay, that surely brings some clarity. I was aware that the `sass-loader` supported both sass/scss and defaulted to scss. But now my question is, why isn't this adjusted so both `lang="sass"` and `lang="scss"` work like they do in the full webpack template? [Here](https://github.com/vuejs-templates/webpack/blob/dist/template/build/utils.js).

I'm assuming this is probably a `vue-loader` default in the end (and also why this is called the `webpack-simple` template) and maybe a [documentation](http://vue-loader.vuejs.org/en/configurations/pre-processors.html#css) problem. It's just a little misleading as I'm sure many people's syntax highlighting doesn't work properly when it thinks it's reading the indentedSyntax when it's not.

![image](https://cloud.githubusercontent.com/assets/8327811/15401311/922930aa-1db4-11e6-8baa-cffbababfaab.png)

It's also seems a little redundant to have to use `lang="sass?indentedSyntax=true"` every time I'd like to use SASS. I'd rather not rely on inline loader requests as others could be using browserify as mentioned [here](http://vue-loader.vuejs.org/en/configurations/pre-processors.html#inline-loader-requests).

**Comment by chrisvfritz** [comment]
Because `vue-loader` doesn't know about specific loaders and their APIs - that's still up to users to configure. This is The Webpack Way in general. Users manually specify in the config a file pattern (usually an extension) that will use a loader or series of loaders.

`vue-loader` does go a bit above and beyond what most loaders do, in that if you specify `lang="whatever"`, it will just look for a `whatever-loader` instead of forcing you to set it up ahead of time in the Webpack config. It gives you access to Webpack's loader config, but it's not an abstraction over it.

I don't think the documentation is misleading. `vue-loader` behaves exactly how it describes. As you mentioned near the end, it sounds like you're simply unhappy about the behavior of *`sass-loader`*. In that particular case, I agree that it's confusing that they've overloaded the word `sass` to represent both the _name of the preprocessor_ and the _name of the now non-default syntax_. That's why in the more advanced template, we've tried to compensate for its wonky API.

**Comment by SimulatedGREG** [comment]
Yeah. Coming from the browserify template, this was just one of these weird differences. Thanks for the help @chrisvfritz .
